[project]
name = "nodenexus"
version = "0.1.0"
description = "Remote server management tool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncssh>=2.24.0",
    "dishka>=1.10.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.0",
    "pytest-asyncio>=0.24.0",
]

[project.scripts]
nodenexus = "main:main"

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["."]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.8.0",
]
